# Utilizează o imagine bază de Redis
FROM redis:latest

# Etichete pentru informații suplimentare despre imagine
LABEL maintainer="Numele Tău <email@example.com>"

# Portul pe care Redis va asculta
EXPOSE 6379

# Comanda de start pentru serverul Redis
CMD ["redis-server"]
